version: "3.9"

services:
  python-dev:
    build: 
      context: ../../
      dockerfile: tools/docker/python.Dockerfile
    container_name: python-dev
    volumes:
      - ../../src/python/:/opt/python_home
    env_file:
      - ../../local.env
    entrypoint: ["sh", "-c", "while true; do echo Looping; sleep 100; done"]
  react-dev:
    build:
      context: ../../
      dockerfile: tools/docker/react.Dockerfile
    container_name: react-dev
    volumes:
      - ../../src/clash-ui:/opt/react_home
    entrypoint: ["npm", "start"]
    ports:
      - 3000:3000 
