version: "3.9"

services:
  python-dev-container:
    build: 
      context: ../../
      dockerfile: tools/docker/python.Dockerfile
    container_name: python-dev
    volumes:
      - ../../src/python/:/opt/python_home
    env_file:
      - ../../local.env
    entrypoint: ["sh", "-c", "while true; do echo Looping; sleep 100; done"]
