version: "3.9"

services:
  python-dev:
    build: 
      context: ../../
      dockerfile: tools/docker/python.Dockerfile
    container_name: python-dev
    volumes:
      - ../../src/python/:/opt/python_home
    env_file:
      - ../../local.env
    entrypoint: ["sh", "-c", "while true; do echo Looping; sleep 100; done"]
  angular-dev:
    build:
      context: ../../
      dockerfile: tools/docker/angular.Dockerfile
    container_name: angular-dev
    volumes:
      - ../../src/clash-ui/:/opt/angular_home
    entrypoint: ["sh", "-c", "while true; do echo Looping; sleep 100; done"]
    ports:
      - 4200:4200
